In [1]:
#import library
from keras.models import Sequential
from keras.utils import np_utils
from keras.utils.np_utils import to_categorical
from sklearn import preprocessing
from keras.layers.core import Dense, Activation, Dropout
from keras.optimizers import RMSprop
import pandas as pd
import numpy as np


Using TensorFlow backend.


In [2]:
#read train.csv
train = pd.read_csv("C:\\Users\\fangj\\Desktop\\Project\\train.csv")
print(train.shape)


#read test.csv
test = pd.read_csv("C:\\Users\\fangj\\Desktop\\Project\\test.csv")
print(train.shape)


#pixels in train.csv
y_train = train.iloc[:,0].values.astype('int32')

#lables in train.csv(header row)
X_train = (train.iloc[:,1:].values).astype('float32')

#pixels in test.csv
X_test = test.values.astype('float32')

#output file 
output = "output1.csv"



(42000, 785)
(42000, 785)


In [3]:
# one hot encoding the labels
y_train = to_categorical(y_train) 
print(y_train)

[[0. 1. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 1.]]


In [4]:
# pre-processing, noemalize pixel values

X_train = X_train /255
X_test = X_test /255


In [5]:
# Design the neural network, we use 12layers, 32 units per layer in this model
model = Sequential()
model.add(Dense(128, input_dim=784)) #28*28 = 784 input dimensions
model.add(Activation('relu'))
model.add(Dropout(0.15))

model.add(Dense(128))
model.add(Activation('relu'))
model.add(Dropout(0.15))

model.add(Dense(128))
model.add(Activation('relu'))
model.add(Dropout(0.15))
model.add(Dense(10)) #10 classes [0-9]
model.add(Activation('softmax'))

Instructions for updating:
Colocations handled automatically by placer.
Instructions for updating:
Please use `rate` instead of `keep_prob`. Rate should be set to `rate = 1 - keep_prob`.


In [6]:
# compile the network, use RMSprop as the optimizer
optimizer = RMSprop(lr=0.001, rho=0.9, epsilon=1e-08, decay=0.0)
model.compile(loss='categorical_crossentropy', optimizer=optimizer, metrics=['accuracy'])
model.fit(X_train, y_train, epochs=10, batch_size=16, validation_split=0.1,  verbose=2)
prediction = model.predict_classes(X_test, verbose=0)

#generate output files
def write_preds(prediction, fname):
    pd.DataFrame({"ImageId": list(range(1,len(prediction)+1)), "Label": prediction}).to_csv(fname, index=False, header=True)

write_preds(prediction, output)


Instructions for updating:
Use tf.cast instead.
Train on 37800 samples, validate on 4200 samples
Epoch 1/10
 - 9s - loss: 0.3386 - acc: 0.8975 - val_loss: 0.1595 - val_acc: 0.9560
Epoch 2/10
 - 9s - loss: 0.1904 - acc: 0.9500 - val_loss: 0.1596 - val_acc: 0.9645
Epoch 3/10
 - 8s - loss: 0.1776 - acc: 0.9581 - val_loss: 0.1621 - val_acc: 0.9664
Epoch 4/10
 - 8s - loss: 0.1763 - acc: 0.9617 - val_loss: 0.1761 - val_acc: 0.9662
Epoch 5/10
 - 8s - loss: 0.1763 - acc: 0.9652 - val_loss: 0.2114 - val_acc: 0.9643
Epoch 6/10
 - 8s - loss: 0.1953 - acc: 0.9643 - val_loss: 0.2091 - val_acc: 0.9690
Epoch 7/10
 - 8s - loss: 0.2170 - acc: 0.9638 - val_loss: 0.2339 - val_acc: 0.9619
Epoch 8/10
 - 8s - loss: 0.2080 - acc: 0.9647 - val_loss: 0.1981 - val_acc: 0.9679
Epoch 9/10
 - 8s - loss: 0.2285 - acc: 0.9654 - val_loss: 0.2274 - val_acc: 0.9688
Epoch 10/10
 - 8s - loss: 0.2161 - acc: 0.9671 - val_loss: 0.2273 - val_acc: 0.9688
